image: WMF 5
init:
clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
install:
- ps: .\install.ps1 -ErrorAction Stop -InformationAction Continue -Verbose
build_script:
- cmd: make
test: off
