version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    working_directory: ~/csm-marks

    steps:
      - run:
          name: Install tools
          command: |
            sudo apt-get install make ghostscript-x

      - checkout

      - run:
          name: Build
          command: make

      - store_artifacts:
          path: /marks/sources/stamps/release/test.pdf
          destination: /
