version: 2
jobs:
  build:
    docker:
      # - image: buildpack-deps:trusty
      - image: ruudk/ghostscript

    working_directory: ~/csm-marks

    steps:
      - checkout

      - run:
          name: Install tools
          command: |
            sudo apt-get update -y
            sudo apt-get install -y curl wget make ghostscript
            bash <(curl -fsSL https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/download.sh)

      - run:
          name: Build
          command: make

      - store_artifacts:
          path: sources/stamps/release/test.pdf
