version: 2
jobs:
  build:
    docker:
      # - image: buildpack-deps:trusty
      # - image: ruudk/ghostscript
      - image: ubuntu:latest
      - image: ubuntu:stable
      # - image: ubuntu:16.04
      # - image: ubuntu:14.04
      - image: centos:latest
      - image: centos:stable
      - image: debian:latest
      - image: debian:stable

    working_directory: ~/csm-marks

    steps:
      - checkout

      - run:
          name: Install tools
          command: |
            sudo apt-get -y update
            sudo apt-get -y install curl wget apt-transport-https
            curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
            curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
            sudo apt-get -y update
            sudo apt-get -y install powershell
            sudo apt-get -y purge make
            sudo apt-get -y install make
            sudo apt-get -y install ghostscript
            sudo apt-get -y upgrade ghostscript
            make --version

      - run:
          name: Build
          command: make

      # - store_artifacts:
      #     path: sources/stamps/release/test.pdf
